2025-06-20 09:25:50,645 - maint_api - ERROR - 获取停机单失败: (pymysql.err.ProgrammingError) (1146, "Table 'tj.downtime_records' doesn't exist")
[SQL: SELECT downtime_records.id AS downtime_records_id, downtime_records.line AS downtime_records_line, downtime_records.shift AS downtime_records_shift, downtime_records.date AS downtime_records_date, downtime_records.status AS downtime_records_status, downtime_records.downtime_minutes AS downtime_records_downtime_minutes, downtime_records.equipment_name AS downtime_records_equipment_name, downtime_records.fault_description AS downtime_records_fault_description, downtime_records.resolution AS downtime_records_resolution, downtime_records.reporter_name AS downtime_records_reporter_name, downtime_records.maintainer_name AS downtime_records_maintainer_name, downtime_records.created_at AS downtime_records_created_at, downtime_records.updated_at AS downtime_records_updated_at, downtime_records.user_id AS downtime_records_user_id 
FROM downtime_records ORDER BY downtime_records.date DESC]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-20 09:36:33,762 - maint_api - ERROR - 获取停机单失败: (pymysql.err.ProgrammingError) (1146, "Table 'tj.downtime_records' doesn't exist")
[SQL: SELECT downtime_records.id AS downtime_records_id, downtime_records.line AS downtime_records_line, downtime_records.shift AS downtime_records_shift, downtime_records.date AS downtime_records_date, downtime_records.status AS downtime_records_status, downtime_records.downtime_minutes AS downtime_records_downtime_minutes, downtime_records.equipment_name AS downtime_records_equipment_name, downtime_records.fault_description AS downtime_records_fault_description, downtime_records.resolution AS downtime_records_resolution, downtime_records.reporter_name AS downtime_records_reporter_name, downtime_records.maintainer_name AS downtime_records_maintainer_name, downtime_records.created_at AS downtime_records_created_at, downtime_records.updated_at AS downtime_records_updated_at, downtime_records.user_id AS downtime_records_user_id 
FROM downtime_records ORDER BY downtime_records.date DESC]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-20 09:36:46,422 - maint_api - ERROR - 获取停机单失败: (pymysql.err.ProgrammingError) (1146, "Table 'tj.downtime_records' doesn't exist")
[SQL: SELECT downtime_records.id AS downtime_records_id, downtime_records.line AS downtime_records_line, downtime_records.shift AS downtime_records_shift, downtime_records.date AS downtime_records_date, downtime_records.status AS downtime_records_status, downtime_records.downtime_minutes AS downtime_records_downtime_minutes, downtime_records.equipment_name AS downtime_records_equipment_name, downtime_records.fault_description AS downtime_records_fault_description, downtime_records.resolution AS downtime_records_resolution, downtime_records.reporter_name AS downtime_records_reporter_name, downtime_records.maintainer_name AS downtime_records_maintainer_name, downtime_records.created_at AS downtime_records_created_at, downtime_records.updated_at AS downtime_records_updated_at, downtime_records.user_id AS downtime_records_user_id 
FROM downtime_records ORDER BY downtime_records.date DESC]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-20 09:36:47,439 - maint_api - ERROR - 获取停机单失败: (pymysql.err.ProgrammingError) (1146, "Table 'tj.downtime_records' doesn't exist")
[SQL: SELECT downtime_records.id AS downtime_records_id, downtime_records.line AS downtime_records_line, downtime_records.shift AS downtime_records_shift, downtime_records.date AS downtime_records_date, downtime_records.status AS downtime_records_status, downtime_records.downtime_minutes AS downtime_records_downtime_minutes, downtime_records.equipment_name AS downtime_records_equipment_name, downtime_records.fault_description AS downtime_records_fault_description, downtime_records.resolution AS downtime_records_resolution, downtime_records.reporter_name AS downtime_records_reporter_name, downtime_records.maintainer_name AS downtime_records_maintainer_name, downtime_records.created_at AS downtime_records_created_at, downtime_records.updated_at AS downtime_records_updated_at, downtime_records.user_id AS downtime_records_user_id 
FROM downtime_records ORDER BY downtime_records.date DESC]
(Background on this error at: https://sqlalche.me/e/20/f405)
